apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devapp
  name: devapp
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30888
    targetPort: 80
  selector:
    app: devapp
  type: NodePort
status:
  loadBalancer: {}
