apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prodapp
  name: prodapp
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30080
    targetPort: 80
  selector:
    app: prodapp
  type: NodePort
status:
  loadBalancer: {}
