apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stageapp
  name: stageapp
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30088
    targetPort: 80
  selector:
    app: stageapp
  type: NodePort
status:
  loadBalancer: {}
