name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_push_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      TAG_NAME: $(date +%Y%m%d%H%M%S)
      REPO_NAME: whaledemo-docker
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$TAG_NAME
      
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:$TAG_NAME
